hub:
  cookieSecret: "SECRET1"
proxy:
  secretToken: "SECRET2"
singleuser:
  image:
    name: DOCKER_IMAGE
    tag: latest
  memory:
      limit: 1G
      guarantee: 1G
  storage:
    capacity: 2Gi
    storageClass:
      parameters:
         type: pd-ssd
  lifecycleHooks:
    postStart:
      exec:
        command: ["git clone https://github.com/dlab-berkeley/python-fundamentals.git"]
